# Generated by Django 5.1.6 on 2025-02-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платёж", "verbose_name_plural": "Платежи"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
