# Generated by Django 5.1.6 on 2025-02-19 21:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Выберите страну",
                max_length=100,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
